In [2]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report , accuracy_score , confusion_matrix , recall_score , precision_score

In [141]:
df = pd.read_csv("../Loan.csv")
print(df.head())
print(df.shape)
print(df.columns)
print(df.info())

   Age   Income  CreditScore  LoanAmount  Dependents     Education  \
0   25  35000.0          620    120000.0           0      Graduate
1   42  72000.0          780    200000.0           2      Graduate
2   35  58000.0          690    150000.0           1      Graduate
3   28  26000.0          590    100000.0           0  Not Graduate
4   50  85000.0          810    250000.0           3      Graduate

  SelfEmployed PropertyArea  PreviousLoans LoanApproved
0           No        Urban              1           No
1           No    Semiurban              0          Yes
2          Yes        Rural              2          Yes
3           No        Urban              1           No
4           No    Semiurban              0          Yes
(13, 10)
Index(['Age', 'Income', 'CreditScore', 'LoanAmount', 'Dependents', 'Education',
       'SelfEmployed', 'PropertyArea', 'PreviousLoans', 'LoanApproved'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            13 non-null     int64
 1   Income         12 non-null     float64
 2   CreditScore    13 non-null     int64
 3   LoanAmount     12 non-null     float64
 4   Dependents     13 non-null     int64
 5   Education      13 non-null     object
 6   SelfEmployed   13 non-null     object
 7   PropertyArea   13 non-null     object
 8   PreviousLoans  13 non-null     int64
 9   LoanApproved   13 non-null     object
dtypes: float64(2), int64(4), object(4)
memory usage: 1.1+ KB
None

In [142]:
df.isna().sum()

Age              0
Income           1
CreditScore      0
LoanAmount       1
Dependents       0
Education        0
SelfEmployed     0
PropertyArea     0
PreviousLoans    0
LoanApproved     0
dtype: int64

In [143]:
df = df.fillna(value={
    "LoanAmount" : df["LoanAmount"].median(),
    "Income" : df["Income"].median()
})
df.isna().sum()

Age              0
Income           0
CreditScore      0
LoanAmount       0
Dependents       0
Education        0
SelfEmployed     0
PropertyArea     0
PreviousLoans    0
LoanApproved     0
dtype: int64

In [144]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
dtype: bool

In [145]:
df.drop_duplicates(inplace=True)

In [146]:
df.head()

,Age,Income,CreditScore,LoanAmount,Dependents,Education,SelfEmployed,PropertyArea,PreviousLoans,LoanApproved
0,25,35000.0,620,120000.0,0,Graduate,No,Urban,1,No
1,42,72000.0,780,200000.0,2,Graduate,No,Semiurban,0,Yes
2,35,58000.0,690,150000.0,1,Graduate,Yes,Rural,2,Yes
3,28,26000.0,590,100000.0,0,Not Graduate,No,Urban,1,No
4,50,85000.0,810,250000.0,3,Graduate,No,Semiurban,0,Yes

In [147]:
x = df.drop("LoanApproved" , axis=1)
y = df["LoanApproved"]

In [148]:
x = pd.get_dummies(x , columns=["Education" , "SelfEmployed" , "PropertyArea" , "PreviousLoans" ] , drop_first=True)
x[["LoanAmount","Income"]]

    LoanAmount   Income
0     120000.0  35000.0
1     200000.0  72000.0
2     150000.0  58000.0
3     100000.0  26000.0
4     250000.0  85000.0
5     130000.0  46000.0
6     180000.0  67000.0
7     110000.0  31000.0
8     230000.0  79000.0
9     145000.0  52000.0
10    170000.0  55000.0
12    160000.0  28000.0

In [149]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [150]:
X_train

,Age,Income,CreditScore,LoanAmount,Dependents,Education_Not Graduate,SelfEmployed_Yes,PropertyArea_Semiurban,PropertyArea_Urban,PreviousLoans_1,PreviousLoans_2
8,45,79000.0,800,230000.0,2,False,False,True,False,False,False
5,31,46000.0,640,130000.0,1,False,True,False,False,True,False
2,35,58000.0,690,150000.0,1,False,True,False,False,False,True
1,42,72000.0,780,200000.0,2,False,False,True,False,False,False
12,27,28000.0,600,160000.0,0,True,False,False,False,True,False
4,50,85000.0,810,250000.0,3,False,False,True,False,False,False
7,29,31000.0,610,110000.0,0,True,False,False,False,False,True
3,28,26000.0,590,100000.0,0,True,False,False,True,True,False
6,39,67000.0,730,180000.0,2,False,False,False,True,False,False

In [156]:
KNN = KNeighborsClassifier(n_neighbors=3)
KNN.fit(X_train , y_train)
Pre = KNN.predict(X_test)

acc = accuracy_score(y_test , Pre)
recall = recall_score(y_test , Pre , pos_label="Yes")
precision = precision_score(y_test , Pre , pos_label="Yes")
print(acc)
print(recall)
print(precision)

0.6666666666666666
0.5
1.0

In [152]:
Tree = DecisionTreeClassifier()
Tree.fit(X_train , y_train)
Pre1 = Tree.predict(X_test)

acc1 = accuracy_score(y_test , Pre1)
recall1 = recall_score(y_test , Pre1 , pos_label="Yes")
precision1 = precision_score(y_test , Pre1 , pos_label="Yes")
print(acc1)
print(recall1)
print(precision1)

1.0
1.0
1.0

,Age,Income,CreditScore,LoanAmount,Dependents,Education_Not Graduate,SelfEmployed_Yes,PropertyArea_Semiurban,PropertyArea_Urban,PreviousLoans_1,PreviousLoans_2
0,25,35000.0,620,120000.0,0,False,False,False,True,True,False
1,42,72000.0,780,200000.0,2,False,False,True,False,False,False
2,35,58000.0,690,150000.0,1,False,True,False,False,False,True
3,28,26000.0,590,100000.0,0,True,False,False,True,True,False
4,50,85000.0,810,250000.0,3,False,False,True,False,False,False
5,31,46000.0,640,130000.0,1,False,True,False,False,True,False
6,39,67000.0,730,180000.0,2,False,False,False,True,False,False
7,29,31000.0,610,110000.0,0,True,False,False,False,False,True
8,45,79000.0,800,230000.0,2,False,False,True,False,False,False
9,33,52000.0,675,145000.0,1,False,True,False,True,True,False
10,36,55000.0,710,170000.0,2,False,False,False,True,False,False
12,27,28000.0,600,160000.0,0,True,False,False,False,True,False