In [1]:
import pandas as pd

In [2]:
data = { 'Name': ['A', 'B', 'C'], 'B': [85, 90, 78], 'City': ['Ahmedabad', 'Delhi', 'Mumbai'] } 
df = pd.DataFrame(data,columns=["A","B","C"]) 
df

     A   B    C
0  NaN  85  NaN
1  NaN  90  NaN
2  NaN  78  NaN

In [3]:
s1 = pd.Series([1,2,3]) 
s2 = pd.Series([4,5,6]) 
df = pd.DataFrame({'col1':s1,'col2':s2}) 
df.set_index("col1",  inplace=True) 
df

      col2
col1
1        4
2        5
3        6

In [55]:
data = { "name": ["Kohli", "Rohit", None, "Rahul"], "runs": [12000, 11000, 3500, 4200], "avg": [None, 48.7, 51.2, 45.3] } 
df = pd.DataFrame(data) 
print(df)

df.fillna(method="bfill",inplace=True)
df

    name   runs   avg
0  Kohli  12000   NaN
1  Rohit  11000  48.7
2   None   3500  51.2
3  Rahul   4200  45.3

C:\Users\Admin\AppData\Local\Temp\ipykernel_16800\2819739381.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill",inplace=True)

    name   runs   avg
0  Kohli  12000  48.7
1  Rohit  11000  48.7
2  Rahul   3500  51.2
3  Rahul   4200  45.3

In [64]:
df.sort_values(by='name', ascending=True)   # ascending
df.sort_values(by='name', ascending=False)  # descending

# col1 ascending, col2 descending
df.sort_values(by='name', ascending=[True])

    name   runs   avg
0  Kohli  12000  48.7
2  Rahul   3500  51.2
3  Rahul   4200  45.3
1  Rohit  11000  48.7