In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame( {
    "std" : [ 'a' , 'b' , 'c' , 'd' , 'e' ],
    'M' : [ 78,90,67,88,90 ],
    "S" : [85,92,70,88,85]
} )
df

  std   M   S
0   a  78  85
1   b  90  92
2   c  67  70
3   d  88  88
4   e  90  85

In [3]:
result = df.sort_values( by=["M" , "S"] , ascending=[False,True] )
result

  std   M   S
4   e  90  85
1   b  90  92
3   d  88  88
0   a  78  85
2   c  67  70

In [4]:
df1 = pd.DataFrame( {
    "City" : ['a','b','c','b','a']
} )

df2 = df1.replace( { 'a' : 'x' , 'b' : 'y' } )
df2['City'].unique()

array(['x', 'y', 'c'], dtype=object)

In [5]:
df1.index[0]

0

In [6]:
len(df1)

5

In [7]:
import pandas as pd
df = pd.DataFrame({
 "Team":["X","Y","X","Y","X"],
 "Runs":[50,60,70,80,90]
})
result = df.groupby("Team")["Runs"].mean()
result["X"]

np.float64(70.0)

In [8]:
import pandas as pd
df = pd.DataFrame({
 "Team":["X","X","Y","Y"],
 "Score":[10,20,30,40]
})
result = df.groupby("Team").nth(1)
# print(result.loc["X"])
result

  Team  Score
1    X     20
3    Y     40

In [13]:
df = pd.DataFrame( [
    [1,2,3,4,5],
    [2,3,4,5,6],
    [None,None,None,None,None]
] )
df.dropna(axis=1,thresh=3,inplace=True)
df.shape[1]

0